Add course enrollment feature: Students can now enroll in courses dir…
eol-uchile/eol-course-program-xblock pull request #2
Opened 2024-05-22 13:53 UTC by tomaspemora

…ectly from the program's course list by clicking on their desired course

2024-05-22 15:05 UTC, fsologureng commented on eolcourseprogram/static/js/src/eolcourseprogram.js
>          $a.append($div);
Esto no es parte del review, pero un `div` no puede ser hijo de un `a`. `DIV` es un elemento de tipo `BLOCK` y `A` es un elemento de tipo `INLINE`, que sólo admite objetos hijo de tipo `INLINE`. Para ese tipo de inclusiones es mejor usar `SPAN`.

2024-05-22 15:24 UTC, fsologureng requested changes

2024-05-22 15:24 UTC, fsologureng commented on eolcourseprogram/static/js/src/eolcourseprogram.js
> +              window.location.href = $a.href;
Es mejor usar `window.location.assign($a.href)` porque maneja mejor el historial de navegación del usuario.

2024-05-22 15:24 UTC, fsologureng commented on eolcourseprogram/static/js/src/eolcourseprogram.js
> +              console.error('Error:', error);
No debería haber una alerta para el usuario de que hay un error? entiendo que el frontend provee una forma de reportar errores...

2024-05-22 15:24 UTC, fsologureng commented on eolcourseprogram/static/js/src/eolcourseprogram.js
> +          var cookies = document.cookie.split(';');
Sugiero simplicar el código al [estilo de MSN](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie#example_2_get_a_sample_cookie_named_test2)

2024-05-22 15:24 UTC, fsologureng commented on eolcourseprogram/views.py
> +        raise Http404(u"Invalid course_key")
La respuesta http a un error en la petición por parte del usuario es 400 (BAD_REQUEST).

2024-05-22 15:24 UTC, fsologureng commented on eolcourseprogram/views.py
> +    # if(not _has_access(request, course_id)):
Si este código podría ser una mejora futura, agregar un comentario con `TODO:` para que quede resaltado en la sintaxis.

2024-05-22 15:24 UTC, fsologureng commented on eolcourseprogram/views.py
> +        mode = course_mode # honor by default
No es posible agregar el modo default del curso?

2024-05-22 15:24 UTC, fsologureng commented on eolcourseprogram/views.py
> +    enrollment.change_mode(course_mode)
de nuevo se define el modo?

2024-05-23 22:11 UTC, tomaspemora commented on eolcourseprogram/views.py
> +        mode = course_mode # honor by default
No existe modo default, pero si existen modos de un curso, generalmente honor. Hay un caso (UEjecutivos) donde queremos usar esta función y necesitamos que la inscripción se haga en modo honor, pero nos dimos cuenta que en otro caso (EPEC) necesitamos que sea verified. 

Voy a implementar una tabla de selectores en el xblock que permita al instructor decidir el modo en el cual quiere que se haga la inscripción en cada curso. Llenaré el selector con los modos disponibles que se hayan configurado previamente en cada curso "destino".

2024-05-24 14:20 UTC, tomaspemora commented
@fsologureng se corrigieron todos los errores y sugerencias mencionadas. Muchas gracias por el feedback, estuvo realmente bueno! 

Me queda pendiente la implementación de tests para el selector de modo de inscripción

2024-05-24 14:23 UTC, tomaspemora commented on eolcourseprogram/static/js/src/eolcourseprogram.js
> +              console.error('Error:', error);
agregué esto 
```$(document).find('.eolcourseprogram_block').append($('<div>').addClass(error-message').text(`Ha ocurrido un error: ${error}`));```

Creo que se podría dejar sin el `${error}` para el usuario en todo caso.

2024-05-24 14:26 UTC, tomaspemora commented on eolcourseprogram/views.py
> +    enrollment.change_mode(course_mode)
corregido

2024-05-24 14:27 UTC, tomaspemora commented on eolcourseprogram/views.py
> +    # if(not _has_access(request, course_id)):
lo saqué porque era justamente lo que no quería. Quería overridear el bloqueo de inscripción para los estudiantes, cuando tuvieran acceso a este bloque.

2024-05-24 14:27 UTC, tomaspemora commented on eolcourseprogram/views.py
> +        raise Http404(u"Invalid course_key")
corregido

2024-05-24 14:42 UTC, tomaspemora commented on eolcourseprogram/static/js/src/eolcourseprogram.js
> +          var cookies = document.cookie.split(';');
Me parece que era MDN? Lo dejé así: `cookieValue = document.cookie.split('; ').find((row) => row.startsWith("csrftoken="))?.split("=")[1];`

Mucho más simple

2024-05-24 14:42 UTC, tomaspemora commented on eolcourseprogram/static/js/src/eolcourseprogram.js
> +              window.location.href = $a.href;
corregido

2024-05-24 14:42 UTC, tomaspemora commented on eolcourseprogram/static/js/src/eolcourseprogram.js
>          $a.append($div);
corregido

2024-05-24 16:01 UTC, fsologureng requested changes
En general lo veo muchísimo mejor, pero el jquery está medio chacreado. Creo que se le puede dar una vuelta de tuerca más.

2024-05-24 16:01 UTC, fsologureng commented on eolcourseprogram/eolcourseprogram.py
> +        logger.info(self.program_courses_enrollment_modes)
El nivel INFO se ve en producción. Si es sólo para hacer debug, cambiar por `logger.debug` y en cualquier caso, agregar texto descriptivo que explique qué es lo que se muestra en la salida, p.e.
```
logger.debug("Program courses enrollment modes: %s",self.program_courses_enrollment_modes)
```

2024-05-24 16:01 UTC, fsologureng commented on eolcourseprogram/models.py
> -            for c in self.courses.all()
Me parece que basta con hacer `self.courses.all().order_by('-id')` y así ahorras memoria y tiempo.

2024-05-24 16:01 UTC, fsologureng commented on eolcourseprogram/static/js/src/eolcourseprogram.js
> +              console.error('Error:', error);
Nunca es bueno matar al mensajero ;)

2024-05-24 16:01 UTC, fsologureng commented on eolcourseprogram/static/js/src/studio.js
> +    var program_courses_enrollment_modes = $(element).find('#courses_list').children().map((idx, el) => {
Creo que esto resulta mucho más simple (y se ve más claro) si defines `program_courses_enrollment_modes` como un arreglo vacío y luego recorres los options `select` con each:
```
var program_courses_enrollment_modes = [];
$("#courses_list select", $(element)).each(function(idx, el){
   program_courses_enrollment_modes[$(el).attr("name")] = $("> option:selected", $(el)).text();
});

2024-05-24 16:01 UTC, fsologureng commented on eolcourseprogram/static/js/src/studio.js
> +    var program_courses_enrollment_modes = $(element).find('#courses_list').children().map((idx, el) => {
Incluso debiera poder usarse `$(el).val()` para obtener el texto.

2024-05-24 16:01 UTC, fsologureng commented on eolcourseprogram/static/js/src/studio.js
> +                                        var modes = program.courses_modes[elem.course_id];
Indentar c/r a `program.courses_list...`.
Tampoco es necesario cambiar la función flecha si envuelves el cuerpo en `{}`. Osea:
```
elem => {
...
```

2024-05-24 16:01 UTC, fsologureng commented on eolcourseprogram/static/js/src/studio.js
> +                                          $('<div>').addClass('select-enrollment')
`li` tampoco puede llevar un `div` como hijo.

2024-05-24 16:01 UTC, fsologureng commented on eolcourseprogram/static/js/src/studio.js
> +                                          .append($("<span>").text('Enrollment Mode'))
Esto debiera ser un `<label>`

2024-05-24 16:01 UTC, fsologureng commented on eolcourseprogram/static/js/src/studio.js
> +                                          .append($("<select>").attr("name", `select_${elem.course_id}`).append(modes.map(mode => {
Sugiero ponerle el nombre `enrollmode_${elem.course_id}` al selector para mejorar su semántica.

2024-05-24 16:01 UTC, fsologureng commented on eolcourseprogram/static/js/src/studio.js
> +                                            if (mode === selected_mode) {option.attr("selected", "selected");} return option;
el return en linea nueva porque no es parte del if, y el scope del if, tb en linea nueva por favor, aunque sea sin paréntesis.

2024-05-24 16:01 UTC, fsologureng commented on eolcourseprogram/static/js/src/studio.js
> +                                        )))));
Creo que se puede mejorar mucho la inteligibilidad del código si se va indentando cada método.
P.e. si se va a llamar más de un método para un mismo elemento, cada nuevo método se pone en linea nueva y se indenta c/r al primero:
```
$ol.append($("<li>")
  .text(`${elem.display_name} (${elem.course_id})`)
  .append(...)
  .append(...)
  ...;
```
Eso permite que si el día de mañana cambias uno de los métodos, no cambias toda la linea con las llamadas.

2024-05-24 16:01 UTC, fsologureng commented on eolcourseprogram/views.py
> +from django.http import HttpResponse, JsonResponse, Http404
Me parece que quedó en desuso.

2024-05-24 16:01 UTC, fsologureng commented on eolcourseprogram/static/js/src/studio.js
> +                                            const option = $("<option>").text(mode).val(mode);
Me parece que `val(mode)` es suficiente, pero no estoy 100% seguro.

2024-05-24 16:03 UTC, fsologureng commented on eolcourseprogram/static/js/src/studio.js
> +    var program_courses_enrollment_modes = $(element).find('#courses_list').children().map((idx, el) => {
Y ahora que vi cómo lo usas dp, sería bueno sacarle el prefijo "select_" al atributo name porque queda más claro que las llaves son course_id's.

2024-05-24 16:14 UTC, fsologureng commented on eolcourseprogram/static/js/src/eolcourseprogram.js
> +          var cookies = document.cookie.split(';');
Me quedé pensando si django no provee un handler más sencillo para el csrftoken incluso en este nivel, porque además es configurable el nombre de la cookie...

2024-05-24 18:01 UTC, tomaspemora commented on eolcourseprogram/eolcourseprogram.py
> +        logger.info(self.program_courses_enrollment_modes)
se me quedó, no es necesario que quede.

2024-05-24 18:32 UTC, fsologureng commented on eolcourseprogram/eolcourseprogram.py
> +        logger.info(self.program_courses_enrollment_modes)
Pero es bueno que quede para debug si fue útil. La cuestión es acostumbrarse a dejar puntos que permitan auditar los datos, incluso en producción si necesitas verlo con datos reales cambiando por un rato el nivel de logging.

2024-05-26 23:17 UTC, tomaspemora commented on eolcourseprogram/static/js/src/studio.js
> +                                            const option = $("<option>").text(mode).val(mode);
No, necesita text también.

2024-05-26 23:17 UTC, tomaspemora commented on eolcourseprogram/views.py
> +from django.http import HttpResponse, JsonResponse, Http404
Se usa en otra parte.

2024-05-26 23:17 UTC, tomaspemora commented on eolcourseprogram/static/js/src/studio.js
> +                                          .append($("<span>").text('Enrollment Mode'))
No será hilar muy fino? De todas maneras lo cambié.

2024-05-26 23:19 UTC, tomaspemora commented on eolcourseprogram/static/js/src/studio.js
> +                                          $('<div>').addClass('select-enrollment')
Según [li#technical_summary](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li#technical_summary) y [div#technical_summary](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div#technical_summary) sí puede.
Además no tira ningún error o warning en https://validator.w3.org/

2024-05-27 13:38 UTC, fsologureng commented on eolcourseprogram/models.py
> +            for c in self.courses.order_by('eolcourseprogram_eolcourseprogram_courses.id')
Por si acaso, en la otra solución lo habías puesto en orden decreciente, por eso yo le puse el `-`.

2024-05-27 13:45 UTC, tomaspemora commented on eolcourseprogram/models.py
> +            for c in self.courses.order_by('eolcourseprogram_eolcourseprogram_courses.id')
ah sí. Había probado esa opción antes y no me había funcionado porque ordenaba respecto al id del otro modelo (CourseOverview), por eso opté por pasarlo a un arreglo y ordenarlo así, pero finalmente encontré esta solución.

2024-05-27 13:50 UTC, fsologureng commented on eolcourseprogram/static/js/src/studio.js
> +                                          .append($("<span>").text('Enrollment Mode'))
Los labels son indispensables para darle accesibilidad a los controles del form. Si no lo haces bien desde el ppio, después cambiarlo es más dificil.

2024-05-27 13:52 UTC, fsologureng commented on eolcourseprogram/static/js/src/studio.js
> +                                          $('<div>').addClass('select-enrollment')
Ah qué bueno, puedo haber estado aplicando sintaxis de html4.

2024-05-27 20:23 UTC, tomaspemora commented on eolcourseprogram/eolcourseprogram.py
> +        logger.info(self.program_courses_enrollment_modes)
se agregó

2024-05-27 20:23 UTC, tomaspemora commented on eolcourseprogram/static/js/src/studio.js
> +    var program_courses_enrollment_modes = $(element).find('#courses_list').children().map((idx, el) => {
corregido

2024-05-27 20:23 UTC, tomaspemora commented on eolcourseprogram/static/js/src/studio.js
> +                                        var modes = program.courses_modes[elem.course_id];
corregido

2024-05-27 20:24 UTC, tomaspemora commented on eolcourseprogram/static/js/src/studio.js
> +                                          .append($("<select>").attr("name", `select_${elem.course_id}`).append(modes.map(mode => {
aplicado

2024-05-27 20:24 UTC, tomaspemora commented on eolcourseprogram/static/js/src/studio.js
> +                                            if (mode === selected_mode) {option.attr("selected", "selected");} return option;
corregido

2024-05-27 20:24 UTC, tomaspemora commented on eolcourseprogram/static/js/src/studio.js
> +                                        )))));
si, de aquí en adelante será el estándar ;)

2024-05-27 20:26 UTC, tomaspemora commented on eolcourseprogram/models.py
> -            for c in self.courses.all()
corregido

2024-05-29 15:15 UTC, fsologureng requested changes

2024-05-29 15:15 UTC, fsologureng commented on eolcourseprogram/eolcourseprogram.py
> +        logger.info(self.program_courses_enrollment_modes)
~~yo lo veo igual, no tiene una explicación del contenido del mensaje...~~
me marié con el código outdated

2024-05-29 15:15 UTC, fsologureng commented on eolcourseprogram/tests.py
> +        self.assertEqual(response.status_code, 302)
Por qué el status correcto es un redirect? apunta al login?

2024-05-29 15:15 UTC, fsologureng commented on eolcourseprogram/views.py
> +                'courses_modes' : {course["course_id"]: list(CourseMode.modes_for_course_dict(course_id=CourseKey.from_string(course["course_id"])).keys()) for course in cp.courses_list_info},
Indentar por favor.

2024-05-29 15:15 UTC, fsologureng commented on eolcourseprogram/eolcourseprogram.py
> +        logger.info(type(self.program_courses_enrollment_modes))
INFO sin explicación del mensaje?

2024-06-17 20:33 UTC, tomaspemora commented on eolcourseprogram/tests.py
> +        self.assertEqual(response.status_code, 302)
Hay que pensar que la gracia de esta nueva funcionalidad es que el estudiante pueda autoinscribirse en los modulos/cursos del programa (que deberían estar cerrados a todo público) solo haciendo click en el link del curso. Es decir, el alumno clickea el curso, se autoinscribe y luego se le redirige al about del curso en cuestión. Por eso puse el 302.

2024-06-17 20:59 UTC, tomaspemora commented on eolcourseprogram/views.py
> +                'courses_modes' : {course["course_id"]: list(CourseMode.modes_for_course_dict(course_id=CourseKey.from_string(course["course_id"])).keys()) for course in cp.courses_list_info},
corregido, próximo commit

2024-06-17 21:00 UTC, tomaspemora commented on eolcourseprogram/eolcourseprogram.py
> +        logger.info(type(self.program_courses_enrollment_modes))
este info se me pasó. No debería ir.

2024-06-17 21:06 UTC, fsologureng commented on eolcourseprogram/tests.py
> +        self.assertEqual(response.status_code, 302)
En ese caso, **si entiendo bien**, es el cliente (javascript) el que redirige sí y sólo si el post fue satisfactorio (status_code = 200). Incluso, muchas apis no responden error http, si no que 200 con un json con el error para que sea el cliente el que decida qué hacer con eso.

2024-06-17 22:34 UTC, tomaspemora commented on eolcourseprogram/tests.py
> +        self.assertEqual(response.status_code, 302)
perfecto. Eso me hace más sentido de hecho. Mi único problema es que de todas maneras estoy usando un redirect en el post, por lo que creo que no voy a obtener un 200

https://github.com/eol-uchile/eol-course-program-xblock/blob/autoenroll/eolcourseprogram/views.py#L184

2024-06-18 16:51 UTC, fsologureng commented on eolcourseprogram/tests.py
> +        self.assertEqual(response.status_code, 302)
Pero ese código es tuyo? por qué no cambiarlo a algo mejor?

2024-06-18 18:03 UTC, fsologureng commented on eolcourseprogram/tests.py
> +        self.assertEqual(response.status_code, 302)
Al menos un redirect 303 (See Other) para que tenga más sentido semántico, pero dado que el código es nuevo y tuyo, por qué no algo más [REST](https://www.reddit.com/r/django/comments/nctfxa/can_a_rest_api_post_request_be_redirected_to_a/)?

2024-06-18 18:08 UTC, tomaspemora commented on eolcourseprogram/tests.py
> +        self.assertEqual(response.status_code, 302)
toda la razón voy con algo más REST. Me dejé llevar por https://github.com/eol-uchile/eol-course-program-xblock/blob/autoenroll/eolcourseprogram/views.py#L159 que era la implementación anterior, pero creo que es mejor opción lo que dices y manejar la redirección desde el browser en función de esa respuesta. Gracias!

2024-06-27 15:24 UTC, fsologureng commented on eolcourseprogram/static/js/src/eolcourseprogram.js
> +          var cookies = document.cookie.split(';');
> Me quedé pensando si django no provee un handler más sencillo para el csrftoken incluso en este nivel, porque además es configurable el nombre de la cookie...

Ya verificamos que la cookie no es configurable y el edx está lleno de usos hardcoded de esa cookie.

2024-06-27 17:20 UTC, fsologureng requested changes
Algo no anda bien en el uso de reverse y eso hay que corregirlo por la via de usar bien las bibliotecas de django y la definición de la view. Pero dejo el review con lo que encontré por el momento, y seguimos en discord con lo otro.

2024-06-27 17:20 UTC, fsologureng commented on eolcourseprogram/static/js/src/eolcourseprogram.js
> +          event.preventDefault();
sigue habiendo espacios al final de la linea :/

2024-06-27 17:20 UTC, fsologureng commented on eolcourseprogram/static/js/src/eolcourseprogram.js
> +            return {
En este punto ya se tiene todo lo necesario para procesar la respuesta. No es necesario un `then` extra para procesar el return que este mismo código inventa.

2024-06-27 17:20 UTC, fsologureng commented on eolcourseprogram/tests.py
> +def encode_course_id(course_id):
Creo que esta función es innecesaria en un contexto de datos controlados como es el test. Sugiero simplificar el escaping de quote directo en la llamada a este uso, salvo que esta función sea empaquetada para un uso permanente en el módulo.

2024-06-27 17:20 UTC, fsologureng commented on eolcourseprogram/tests.py
> +
salto de linea extra innecesario.

2024-06-27 17:20 UTC, fsologureng commented on eolcourseprogram/views.py
> +                course["course_id"]: list(
indentación de esta linea. Además, es necesario envolver todo en un list cuando keys() ya retorna una list?

2024-06-27 19:22 UTC, tomaspemora commented on eolcourseprogram/views.py
> +                course["course_id"]: list(
en Python 3 keys() retorna un objeto que se llama dict_keys.

2024-06-27 22:38 UTC, fsologureng commented on eolcourseprogram/static/js/src/eolcourseprogram.js
> +          // window.location.href = href;
quedó este código comentado que me parece que ya es inútil

2024-06-27 22:38 UTC, fsologureng commented on eolcourseprogram/static/js/src/eolcourseprogram.js
> +
espacios en blanco de más

2024-07-03 17:18 UTC, fsologureng approved these changes

2024-07-03 17:38 UTC, merged